name: Scala CI

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build:
    name: Scala unit tests with Java ${{ matrix.jdk }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: [8, 11, 13]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - run: rm replicate/src/test/scala/replicate/ReplicateSpec.scala
    - name: Run tests
      run: sbt test
  assemble:
    name: Assembly test
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Assemble programs
      run: sbt assembly
