name: Scala CI

on:
  push:
    branches:
      - renovate/**
  pull_request:
  merge_group:

jobs:
  build:
    name: Scala unit tests with Java ${{ matrix.jdk }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        jdk: [11, 13, 19]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - run: rm replicate/src/test/scala/replicate/ReplicateSpec.scala
    - name: Run tests
      run: sbt test
  assemble:
    name: Assembly test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Assemble programs
      run: sbt assembly
