name: Scala CI

on:
  pull_request:
  merge_group:

jobs:
  build:
    name: Scala unit tests with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17, 20]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - run: rm replicate/src/test/scala/replicate/ReplicateSpec.scala
    - name: Run tests
      run: sbt ++2.13 test
  assemble:
    name: Assembly test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - name: Assemble programs
      run: sbt ++2.13 assembly
