name: Scala CI

on:
  push:
    branches:
      - staging
      - trying
      - complete-tests

jobs:
  build:
    name: Scala unit tests with Java ${{ matrix.jdk }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: [8, 11, 13]
    services:
      couchdb:
        image: couchdb:2.3.1
        ports:
          - 5984:5984
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Install steenwerck.conf
      run: echo "${{ secrets.STEENWERCK_CONF }}" > steenwerck.conf
    - name: Run tests
      run: sbt test
  assemble:
    name: Assembly test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Assemble programs
      run: sbt assembly
